### PR TITLE
added: ability to pass submit context to onSubmit handler

### LINKED ISSUE #214: 2 submit buttons
Is there anyway to have 2 submit buttons in 1 form?

### LINKED ISSUE #1792: Submit Payload
### Current Behavior

People do hack with `setTimeout` + `setFieldValue` - #214 

### Desired Behavior

It would be great if we have an option to pass something with `submitForm(payload)` to submit handler or get an event from submitted button.

### Who does this impact? Who is this for?

For all people who need to render two submit buttons with different submitting logic!

### PR DESCRIPTION
**Pull request by avasuro**
This closes #214, closes #1792

-----
[View rendered docs/api/formik.md](https://github.com/avasuro/formik/blob/feat/add-submit-context/docs/api/formik.md)

### CODE REVIEW

**Comment by avasuro** [comment]
Not sure that this functionality should be included in Formik out of the box, but as far as I see from opened tickets this functionality will be useful for many users. So here is my proposal how it can be implemented.

In addition to this there can be one thing to improve - in `handleSubmit` method we can use clicked button name as submitContext (this way instead of this `onClick={(e) => submitForm(e.target.name)}` users will be able to do this `onClick={handleSubmit}`), but again - not sure that it is worth implementing.

Please, share your thoughts about this, and feel free to reject this PR if you are sure that this feature is not enough generic to be included in this library.

**Comment by johnrom** [comment]
I am fine with this API and agree that if we implement it, handleSubmit should pass `Event` by default.

**Comment by avasuro** [comment]
@johnrom 

Yes, you are right, passing an Event object will be the best choice.

Unfortunately I removed my fork of this repo, so can't add new commits to this PR. I forked repo again, and added new changes for `handleSubmit` method. I think you (or any administrator of this repository) have some rights to update this PR to include necessary changes. Could you please do this?

Here is new commit: https://github.com/avasuro/formik/commit/532d3e51395056e434dbed17da997fdc8efe3e6a

Thank you.

**Comment by johnrom** [comment]
Hi @avasuro, unfortunately we don't have permission to update the source repo. You'll have to open another PR. Please close this PR once you do (a link to it would be helpful). Thanks for your contribution!

**Comment by avasuro** [comment]
Opened another PR with additional changes: https://github.com/jaredpalmer/formik/pull/2437

**Pull request closed without merging**
