### PR TITLE
Fix FastField.handleBlur leading to undefined errors and invalid forms

### PR DESCRIPTION
**Pull request by bobbyrenwick**
# Bug
Using `FastField` in a `Formik` form with `validateOnBlur` leads to forms being invalid when Fields are blurred without inputting anything.

# Current Behaviour
If you render the following form and then click into and out of the name field, you'll see that eventually `formikProps.errors` is logged to the console as `{ name: undefined }`. This means that when you have a form with validation you end up with the form being invalid just because someone touched a field.

```js
<Formik
  initialValues={{ name: "formik" }}
  render={(formikProps) =>  {
      console.log(formikProps.errors);
      return (
        <FastField name="name" type="text" />
      );
  }}
/>
```

# Desired Behaviour
`FastField.handleBlur` causes errors to be removed from `FormikBag.errors`, nested to any level, when `FastField.state.error === undefined`. 

# Solution
I added an `unsetIn` function that is similar to `unset` from `lodash`, but it needs to do cleanup along the way. If you have nested form values and the key you're unsetting is the final one in that object, then that field.name, error object pair also needs to be removed so that there are no empty objects in `FormikBag.errors`.

I'm not particularly happy with how this code reads, so any suggestions for changes to how it works would be most welcome!

Formik Version: 1.0.0-beta-1
React Version: 16.2.0
OS: OS X 10.11.6
Node Version: 9.11.1
Package Manager and Version: npm@5.6.0

### CODE REVIEW

**Comment by ericbiewener** [comment]
Looks like this is a problem with non-FastField components as well: https://github.com/jaredpalmer/formik/issues/558

**Comment by jaredpalmer** [comment]
Can we reopen this?

**Comment by jaredpalmer** [comment]
Pinned for v2

**Comment by jaredpalmer** [comment]
Pin

**Pull request closed without merging**
