### PR TITLE
fix-docs: return type of setValue in docs did not match the function typing

### PR DESCRIPTION
**Pull request by DavideFrancescon**
[Function return](https://github.com/jaredpalmer/formik/blob/main/packages/formik/src/types.tsx#L91 )
Docs before changes: `setValues: (fields: React.SetStateAction<{ [field: string]: any }>, shouldValidate?: boolean) => void`
Closes: #3846

### CODE REVIEW

**Review by probablyup — APPROVED** [review]
Thank you!

**Comment by probablyup** [comment]
@DavideFrancescon for whatever reason your branch seems to be having issues staying up to date, could you merge `main` for me to get this good for merging?

**Comment by DavideFrancescon** [comment]
> @DavideFrancescon for whatever reason your branch seems to be having issues staying up to date, could you merge `main` for me to get this good for merging?

It SHOULD be okay now, hopefully, let me know if it works! 
Thanks for your time

**Comment by DavideFrancescon** [comment]
@probablyup I guess it does not work :') 

I don't think I can do much about this as mine was only a small change and surely didn't cause this much of a performance issue.

**Comment by probablyup** [comment]
> @probablyup I guess it does not work :')
> 
> I don't think I can do much about this as mine was only a small change and surely didn't cause this much of a performance issue.

I think it's just some transient weirdness, rerunning the job.

**Comment by DavideFrancescon** [comment]
> > @probablyup I guess it does not work :')
> > I don't think I can do much about this as mine was only a small change and surely didn't cause this much of a performance issue.
> 
> I think it's just some transient weirdness, rerunning the job.

What if I try adding a new commit with like a new-line somewhere just to reset the algorithm?

**Comment by probablyup** [comment]
Going to fix the check to not run when it's unnecessary → https://github.com/jaredpalmer/formik/pull/3880

**Pull request merged**
