### PR TITLE
Spread extra Field props to render prop and children-as-function

### LINKED ISSUE #942: Field ownProps are not passed into render function
According to documentation:
Field's render props are an object containing:
- field: An object containing onChange, onBlur, name, and value of the field
- form: The Formik bag.
- **Any other props passed to field**

## Current Behavior

**myCustomProp** is not passed to the render function 

```
<Field
     name="lastName"
     myCustomProp="YES!"
     render={({ field, form, ...ownProps }) =>
          "This is not passed in: " + ownProps.myCustomProp
     }
/>
```

BUT it is, when using custom component:

```
<Field name="firstName" component={CustomInputComponent} />

const CustomInputComponent = ({ field, form, ...ownProps }) =>
  "Works here: " + ownProps.myCustomProp;
```

## Steps to Reproduce

- run code in CodeSandbox
- Following result appears:

> Works here: YES!
> but not here: undefined

## Expected behavior
- Following result appears:

> Works here: YES!
> but not here: YES!

## Additional context

**CodeSandbox Link**:
[Edit llp0zjqrp9](https://codesandbox.io/s/llp0zjqrp9)

---

- Formik Version: 1.3.0
- React Version: 16.3.2
- TypeScript Version: N/A
- Browser and Version: Chrome 69.0.3497.100 (64bit)
- OS: Win 10
- Node Version: 8.12.0
- Package Manager and Version: Yarn 1.10.1

### PR DESCRIPTION
**Pull request by christianchown**
Closes #942 (which is marked as _wontfix_), and is a near-duplicate of #957 from @adsingh (which was closed without merge). 

So given that, I better make a good pitch for you not to hit the insta-close button! 

There's been discussion in #957, and here are some reasons why we'd like this PR merged.

1. **Consistency between the 3 ways to render using `Field`**
Of the three ways to render things with `Field`, additional props ([as per the docs](https://jaredpalmer.com/formik/docs/api/field)) 
get passed through to 1 of them - `component`, which gets `...bag` and `...props` below

https://github.com/jaredpalmer/formik/blob/5cba633bbb3d06193fccf8b0e54fa91b2c0b6457/src/Field.tsx#L183-L187

but the other 2 don't. _render_ prop and _children-as-function_ just get `bag`, no `props`:

https://github.com/jaredpalmer/formik/blob/5cba633bbb3d06193fccf8b0e54fa91b2c0b6457/src/Field.tsx#L165-L171

2. **A composite component can't decorate `Field`**.
[The main reason given behind closing #957](https://github.com/jaredpalmer/formik/pull/957#issuecomment-427029872) was that you could pass addditional props directly to a render function via a closure. This does not hold if you want to use `Field` compositionally. I have a case - https://github.com/jaredpalmer/formik/pull/957#issuecomment-430533580 - where I have a `DecoratedField` component that renders a `Field` where the render prop is injected by a consumer... however I also want to pass some of `DecoratedField`'s state to this render prop function. It cannot be done, because all it gets is `bag`

3. **Adding and removing extra props to a `FastField` causes it to rerender, but those props can't then be used _in_ the render**
Here's the line in `shouldComponentUpdate` that forces the rerender, as per the docs. It seems anachronistic not to be able to use the values that cause the rerender, unless they're `Field` ones.
https://github.com/jaredpalmer/formik/blob/4cabec1881f47ee603ae6ab97b8eb92652c8bcc7/src/FastField.tsx#L120

Anyway, hope you'll consider the above

ps loving your work

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Formik’s render props work exactly like React Router’s work.  In the future, we will deprecate render entirely.

**Comment by christianchown** [comment]
Just dug through React Router's `Route`, and that doesn't pass props through, but does have a mechanism for proving decoration by [spreading its `staticContext`](https://github.com/ReactTraining/react-router/blob/9d278b4b110f38479725fe5a1104990c2f3e76c2/packages/react-router/modules/Route.js#L17-L31)

v2 (and hooks?) will likely make all this moot, of course, but until then...

**Comment by jaredpalmer** [comment]
Again, this was a design decision. You can write your own version of Field with this behavior if you’d like with connect().

**Comment by christianchown** [comment]
Hi - at the moment, I am using `component`, as these get `props` as well as `bag`. Should the other two ways to render - render props and children-as-function - not get the same `props` along with `bag`?

**Comment by jaredpalmer** [comment]
This introduces redundancy. All props can be accessed through a closure in the case of render and children as they are already in scope. There is no need to send them.

**Pull request closed without merging**
