### PR TITLE
Added onChange callback & validation in componentDidMount

### PR DESCRIPTION
**Pull request by morgs32**
Also added storybook.
image

### CODE REVIEW

**Comment by morgs32** [comment]
Can do. Also I didn't mean for storybook to serve as docs. It's been really handy as a development tool, something you would spin up locally. When you're working on this, and experimenting with the UI, are you doing a `yarn link` and always using the compiled files? I was looking for an easy way to run `formik` locally, being able to drop breakpoints and debug it via dev tools, etc. If you would prefer not to use storybook, perhaps a standalone app to run locally? Thoughts?

**Comment by jaredpalmer** [comment]
I try not to rely too hard on UI while writing new stuff. This forces me to think through tests. If I need to link, I throw it in a local branch of React-parcel-example with typescript. The docs site also has runnable examples like React Router docs, so storybook is somewhat redundant

**Comment by jaredpalmer** [comment]
componentWillUpdate is being deprecated. However, I’m def open to a separate storybook PR

**Comment by jaredpalmer** [comment]
onChange encourages ppl to sync state in 2 places which usually never works out. I’m going to push up my work on the state reducer / middleware and would love to get your input on that though.

**Comment by morgs32** [comment]
@jaredpalmer I see this RFC you have... https://github.com/jaredpalmer/formik/issues/401
Let me know if that's on a branch, I'm interested...

**Pull request closed without merging**
