### PR TITLE
Fix deprecated type in React 18

### LINKED ISSUE #3546: Namespace 'React' has no exported member 'StatelessComponent'.
## Bug report

The StatelessComponent type was removed in react update 18 - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

### Current Behavior
Error when building app :
`node_modules/formik/dist/withFormik.d.ts(58,77): error TS2694: Namespace 'React' has no exported member 'StatelessComponent'.`

### Expected behavior
Build without errors.

### Reproducible example
Following the formik documentation - https://formik.org/docs/guides/typescript
https://codesandbox.io/s/hardcore-bhabha-kobk3m?file=/src/MyForm.tsx
Deploy sandbox to preview

### Suggested solution(s)
I don't know how to replicate it in codesandbox, but in a local environment in 
`node_modules/formik/dist/withFormik.d.ts` on line 58 replace` React.StatelessComponent<P>` by `React.FunctionComponent<P>`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.9
| React            | 18.0.0
| TypeScript       | 4.6.3
| Browser          |  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
| npm/Yarn         | yarn
| Operating System | Windows

### PR DESCRIPTION
**Pull request by alaanescobedo**
Replace StatelessComponent by FunctionComponent in withFormik.tsx
fix #3546 

PR to solve the problem with the removed type in react 18
I saw that you have a build/types branch, but it hasn't changed since 2020, so I did the direct PR in master

### CODE REVIEW

**Comment by Alcas1** [comment]
Can we get this merged? This is blocked multiple deployments

**Comment by kanishkad** [comment]
Can we get this merged please? This is blocking production deployments.

**Comment by colebowl** [comment]
Hi @jaredpalmer / @johnrom - Are you able to provide guidance on what is required to get this pushed through? `StatelessComponent` has been removed from React 18 after being long ago deprecated.

FYI - `<StatelessComponent />` was deprecated in November 2018 (Around React 16.8) in favour of `<FunctionalComponent />`. See for details: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30364

All React React 18 projects are now failing. It would be great if we could get this merged in ASAP. I'm happy to help with any tasks required to get this completed

Thanks!

**Comment by colebowl** [comment]
Thanks, @Poky85  - Yeah that's true but this PR has been open for a couple of months to change of code. It would be great if we could get the PR merged in so that we don't need to use the workaround!

**Comment by colebowl** [comment]
@eonwhite  - Ian - I'm flagging you in here to see if you're able to help us get this moved forward? Thanks

**Review by probablyup — APPROVED** [review]

**Review by probablyup — APPROVED** [review]

**Comment by probablyup** [comment]
Needs a changeset

**Pull request merged**
