### PR TITLE
Add FieldHelpers object to useField

### PR DESCRIPTION
**Pull request by drivasperez**
Implements the change suggested in #1907.

Adds a third object ("helpers") to the array produced by useField. This
exposes three helper functions to allow you to imperatively change the
field in question:

  1) setValue
  2) setTouched
  3) setError

E.g.:
```
const MyInput = props => {
  const [field, meta, helpers] = useField(props);

  return (
    <input
      {...field}
      onFocus={() => {
        helpers.setTouched(true);
      }}
      onBlur={e => {
        if (e.currentTarget.value === "hi") {
          helpers.setError("Hey");
        }
      }}
      onChange={e => {
        helpers.setValue(e.target.value);
      }}
    />
  );
};
```

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Add docs and this is lgtm

**Comment by slorber** [comment]
+1000, was just reimplementing this in my code, as many times it's not possible to use handleChange(domEvent) (RN for example, but also dropdowns or more complex form items)

**Comment by drivasperez** [comment]
@jaredpalmer How does this look?

**Comment by VanTanev** [comment]
@drivasperez @jaredpalmer Was there a particular reason you decided not to include the `shouldValidate?: boolean` optional attribute for these helpers? It seems like it would have made sense to have the full functionality of the `FormikContext` methods.

**Comment by drivasperez** [comment]
Oversight on my part, I think. I can add it.

**Comment by MikeSuiter** [comment]
@drivasperez I just started converting from Formik 1.5.8 to 2.1.2 and since you implemented `setValue` have a question. I have our custom `Field` which adds format and normalize functionality to a field which worked in 1.5.8. Now I'm trying to convert it and `setValue` puts it in an infinite loop re-rendering `Field`. 

Here is my component and `Component` will be a formik-material-ui component. It works just fine unless the format property is set which causes the infinite loop. The parent component doesn't re-render during the infinite loop. Any ideas?

```
const Field = ({ component: Component, name, format, normalize, useContext, onChange, validate, ...otherProps }) => {
  const [field, meta, helpers] = useField(name);

  console.log('Field render');

  if (format) {
    helpers.setValue(format(field.value));
  }

  return <Component name={name} {...otherProps} />;
};
```

**Comment by drivasperez** [comment]
@MikeSuiter `setValue` triggers a re-render, so unconditionally calling it in the render function will cause an infinite loop. You could do something like this:

```jsx
const Field = ({ component: Component, name, format, normalize, useContext, onChange, validate, ...otherProps }) => {
  const [field, meta, helpers] = useField(name);

  React.useEffect(() => {
    if (format && field.value !== format(value)) {
      helpers.setValue(format(value));
    }
  })

  return <Component name={name} {...otherProps} />;
};
```
But I think more likely you want something like this:
```jsx
const Field = ({ component: Component, name, format, normalize, useContext, onChange, validate, ...otherProps }) => {
  const [field, meta, helpers] = useField(name);
  
  function handleChange(value) {
    if (format) {
      helpers.setValue(format(value))
    } else {
      helpers.setValue(value);
    }
  }

  return <Component name={name} {...otherProps} onChange={handleChange} />;
}
```
Does that help?

**Comment by MikeSuiter** [comment]
@drivasperez Thanks for the response and I thought it would be easy to do your second solution but the Formik Material-UI library doesn't pass onChange down to Formik. This is my first dive into hooks so I have some learning to do!

https://stackworx.github.io/formik-material-ui/docs/guide/faq

In your first solution you're using value but I'm not sure where that's coming from.

**Comment by drivasperez** [comment]
Oh, sorry, that was a typo. I meant `field.value` instead of `value`. The idea is to check if the field’s value is formatted and, if not, to apply the effect.

**Pull request merged**
