### PR TITLE
Updating documentation of submitForm

### PR DESCRIPTION
**Pull request by FBerthelot**
Hello,

A little first PR :)

Updating documentions according to #486.

Have a nice day

### CODE REVIEW

**Comment by hinok** [comment]
@jaredpalmer @FBerthelot 

At the moment documentation says that `submitForm` returns a rejected promise if form is invalid but it looks that it "eats" errors and only set state `this.setState({ isSubmitting: false });`.

**Lines:** https://github.com/jaredpalmer/formik/blob/v1.5.4/src/Formik.tsx#L426-L450

This misleading information shows up on

```
- v1.5.4 (https://jaredpalmer.com/formik/docs/api/formik#submitform-promise)
- v1.5.3 (https://jaredpalmer.com/formik/docs/1.5.3/api/formik#submitform-promise)
```

v1.5.2 looks okay (https://jaredpalmer.com/formik/docs/1.5.2/api/formik#submitform-void), no information about returning promise.

Was that PR merged too early?

**Comment by FBerthelot** [comment]
Hi @hinok ,

Submit form return the promise from runValidations. This Promise is here => https://github.com/jaredpalmer/formik/blob/v1.5.4/src/Formik.tsx#L267

I believed the  RunValidation reject promise when the form is invalid, it's make sense.

Sorry If I made a mistake. I was certain at the time.

**Comment by hinok** [comment]
It returns a promise but it's always resolved https://github.com/jaredpalmer/formik/blob/v1.5.4/src/Formik.tsx#L299

so something like

```js
submitForm()
  then(() => {
    // this is always fired, it doesn't matter if form is valid or not
  })
  .catch((errors) => {
    // this will never be fired
  });
```

**Comment by ivan-oliveira** [comment]
@FBerthelot 

Looking at the code for runValidations it will resolve the promise with the errors: 
`return promise
      .then((errors: FormikErrors<Values>) => {
        if (this.didMount) {
          this.setState(prevState => {
            if (!isEqual(prevState.errors, errors)) {
              return { errors };
            }
            return null; // abort the update
          });
        }
        return errors;
      })
      .catch(x => x);
`

In turn submitForm() will always resolve as well.

**Comment by FBerthelot** [comment]
@ivan-oliveira look at #1580 ;)

**Pull request merged**
