### PR TITLE
Bump deps, fixes @types/react 16.4

### PR DESCRIPTION
**Pull request by jaredpalmer**
Bump to 

- React 16.4.5 
- TS 3.1.0
- TSLint / TSLint React

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Is yarn down? wtf.

**Comment by jaredpalmer** [comment]
@weswingham I know it’s not your space but do you know why Formik’s render prop is now an implicitly any when it was inferred before?

**Comment by weswigham** [comment]
The new react .d.ts uses a new entry point in the jsx namespace to allow for inference from `defaultProps` (using conditional types), and something about how that type + formik's type are written prevents inference from succeeding when defaultProps are present. TS 3.1 has a change that _might_ help (it helps a simplified example), but it also might not be enough on it's own (since the types are quite complicated).

**Comment by weswigham** [comment]
Fyi, this should be fixed in TS 3.1 which aughta release very soon.

**Comment by jaredpalmer** [comment]
Cool. I’ll wait.

**Comment by jaredpalmer** [comment]
@wesigham it seems that with the new guard / function change, i can’t figure out how type optional render props (ie children?, component?, render?). Any suggestions?

**Pull request merged**
