### PR TITLE
Change setIn to use clone instead of cloneDeep.

### PR DESCRIPTION
**Pull request by danifus**
Improve performance of ``setIn`` by shallow copying unchanged siblings
along the path to be updated.

Could enable significant performance improvements when implementing
``shouldComponentUpdate`` methods for nested structures as it allows direct
comparison of object / arrays to see if there has been changes to any of
their child values (because unchanged objects retain the same js
reference).

### CODE REVIEW

**Comment by danifus** [comment]
Hi,

This is useful when ``fieldArray`` items are expensive to render. It allows the component which renders the ``fieldArray`` item to compare the new and old item by reference, simplifying the implementation of ``shouldComponentUpdate`` for that component.

From looking at the code (and passing tests) I think it is ok but I'd like to get your input on whether you think this change may have unintended side effects.

**Comment by jaredpalmer** [comment]
I need to look up the issue. However, I think it was changed to deepClone for a reason.

**Comment by jaredpalmer** [comment]
We should add a comment either way as to why or why not since I can’t remember off the top of my head

**Comment by danifus** [comment]
That is a good idea.

How about a comment like:
```
/**
 * Deeply set a value from in object via it's path.
 * @see https://github.com/developit/linkstate
 * If the value at `path` has changed, return a shallow copy of obj with
 * `value` set at `path`. If `value` has not changed, return the original
 * `obj`.
 *
 * Existing objects / arrays along `path` are also shallow copied. Sibling
 * objects along path retain the same internal js reference. Because new
 * objects / arrays are only created along `path`, we can test if anything
 * changed in a nested structure by comparing the object's reference in
 * the old and new object, similar to how russian doll cache invalidation
 * works.
 */
export function setIn(obj: any, path: string, value: any): any {
...
}
```

**Comment by jamiedavenport** [comment]
Does this have implications for issues such as #905?

**Comment by danifus** [comment]
Depends how deeply the incompatible Immutable.js object is nested within the Draft.js object that gets put into Formik's `values`. `clone` and `cloneDeep` both use `baseClone` underneath which [still accesses `.length`](https://github.com/lodash/lodash/blob/master/.internal/arrayLikeKeys.js#L23), so the only way this change would help is if the Draft.js object in `values` is not itself the incompatible object and can be shallow copied (avoiding the incompatible Immutable.js object completely).

I've never used Draft.js so I can't tell you how likely that is.

**Comment by jamiedavenport** [comment]
I've run my project using `danifus:master` and I don't have the performance issues when using custom Draft.js inputs.

**Comment by kenta88** [comment]
Hi guys, there are any update about this? 
There are any intention to merge this one? 

I have the same issue with draft.js and this will help. In case this will not be merged, i'll have a possible workaround for that. (basically avoiding the use of FieldArray)

Thanks

**Comment by danifus** [comment]
Hi, I've been using this in my private projects for a while and haven't noticed any issues so far.

Are there any parts of the code base that you suspect could be affected by this change that you would like me to write some tests for?

**Comment by danifus** [comment]
Was this the previous issue you were thinking of: https://github.com/jaredpalmer/formik/issues/364? That issue was setting a nested value would mutate the parent instead of creating a new object.

`clone` avoids that bug making a shallow copy of the objects along the update path so no object is mutated in place.

The test added for that issue is still passing: https://github.com/jaredpalmer/formik/blob/master/test/utils.test.tsx#L180

**Comment by dzg** [comment]
Is there documentation for `setIn`?

How would I set a value for a single property of a single object of an array of objects?
I.e.,

**Comment by jaredpalmer** [comment]
@danifus this is great. Thanks! Pushing out a new release now

**Pull request merged**
