### PR TITLE
Fix initialValues ref when `enableReinitialize` is true

### PR DESCRIPTION
**Pull request by kimochg**
### What

enableReinitialize should work now, ~~and an enableReinitialize example is added.~~

### Issues

https://github.com/jaredpalmer/formik/issues/1565
https://github.com/jaredpalmer/formik/issues/1528

### CODE REVIEW

**Comment by falldowngoboone** [comment]
Tests probably need to be updated as well.

**Comment by Andreyco** [comment]
wasn't fix for this merged already by @jaredpalmer ?

**Comment by jaredpalmer** [comment]
I lost track

**Comment by jaredpalmer** [comment]
It’s being deprecated in v2

**Comment by kimochg** [comment]
@jaredpalmer Example removed.  Nicely check it again. btw, is there a new API for reinitialvalue or formik is no longer support reinitialvalue?

**Comment by jaripekkala** [comment]
https://github.com/jaredpalmer/formik/pull/1583#issuecomment-499374210

> In v2, reinitialize has be deprecated with a warning in favor of initialXYZ props. If defined, it keeps the v1 behavior, otherwise the behavior is disabled in favor of initialValues, initialErrors, and initialStatus. If you change those, then the form will reset. This also fixes initial dirty/pristine confusion.

I'm confused.

**Comment by jaredpalmer** [comment]
If you pass true/false to `enableReinitalize`, it will work but will show a warning in v2.

**Comment by ArnaudBarre** [comment]
> If you change those, then the form will reset. This also fixes initial dirty/pristine confusion.

So it sounds like enableReinitalize is true by default in v2 ?

**Comment by jaripekkala** [comment]
It clearly isn't working on the latest release if thats so

https://codesandbox.io/embed/formik-codesandbox-template-fgk8x

**Comment by jaredpalmer** [comment]
Actually I think I misspoke. The form will _not_ reset in v2.

**Comment by ArnaudBarre** [comment]
So is there another way to achieved this behaviour without using a deprecated parameter ?

**Comment by jaredpalmer** [comment]
I'M SORRY. I got confused when reading this too. Total Brain fart. enableReinitialize is not deprecated and works like v1. `isInitialValid` is being deprecated. My bad.

**Pull request merged**
