### PR TITLE
Adds 'submitForm' to FormikBag

### PR DESCRIPTION
**Pull request by ctrlplusb**
Similar to the custom `resetForm` action.

Useful in cases where you aren't depending on a DOM element to perform the submit.

I was looking to add a test, but I see you are still forming your strategy here.

--

Great library @jaredpalmer and @eonwhite 👍

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Happy to update docs if you are interested in merging 👍

**Comment by jaredpalmer** [comment]
Thanks Sean. Can you update the readme and put submit form in it place (alphabetically) in the API section?

**Comment by ctrlplusb** [comment]
@jaredpalmer ping 👍

**Comment by ctrlplusb** [comment]
Hmmm, my editor's merge conflict resolver threw a 🔧 at me, apologies for the README merge noise.  Looks good now.

**Comment by jaredpalmer** [comment]
@ctrlplusb So after some thought, I haven't been able to come up with a situation when it would be useful to call `submitForm` manually over just using `handleSubmit`. Can you give an concrete example use case?

**Comment by ctrlplusb** [comment]
Sure thing @jaredpalmer, it's great for you to question these things. 👍

I guess anywhere were we don't have a natural DOM event action trigger. Auto save triggers, and pre-navigation saving etc?  I could just call the handleSubmit but I just have to stub out the event (`{ preventDefault: () => undefined }`) due to the `e.preventDefault()` call at the top of `handleSubmit`.

**Comment by ctrlplusb** [comment]
I'm gonna close this for now.  Let's see if there is any more demand. It's easy enough to add.

**Comment by anhldbk** [comment]
@ctrlplusb Great PR! I think it's a must-have feature in `formik`

@jaredpalmer Here's the usecase: I have a tabbed interface  like the one below:

screenshot from 2017-07-10 20-42-57

There're action buttons in the bottom (for both step 1 and step 2) and there's no button inside each step. Step 2 uses a `formik` form. When users finish all steps, they click on button `Proceed`. I want the form to validate provided data before doing anything else ...

Well please merge this PR.

**Comment by anhldbk** [comment]
@ctrlplusb Hey, I invoke `submitForm` and my `handleSubmit` is not called. Anything wrong?

**Comment by anhldbk** [comment]
@ctrlplusb Great! It works. I think `submitForm` should return a Promise.

```js
// declaration
submitForm: () => Promise<any>; 

// implementation 
submitForm = () => {
    this.setState({
        touched: touchAllFields(this.state.values),
        isSubmitting: true
    });
    const { values } = this.state;
    // Validate against schema
    return validateFormData<Values>(values, validationSchema).then(
        () => {
            this.setState({ errors: {} });
            const result = mapValuesToPayload(this.state.values);
            handleSubmit(result, {
                setTouched: this.setTouched,
                setErrors: this.setErrors,
                setError: this.setError,
                setSubmitting: this.setSubmitting,
                setValues: this.setValues,
                resetForm: this.resetForm,
                submitForm: this.submitForm,
                props: this.props
            });
            return result; // ==> modified to return results
        },
        (err: any) => {
            this.setState({
                isSubmitting: false,
                errors: yupToFormErrors(err)
            });
            return Promise.reject("Error when validating form");
        }
    );
};
```

In my case, I don't provide `formik` with may `handleSubmit`. I use `submitForm` instead`

```js
    this._form.submitForm().then(
      data => {
        console.log("success", data);
      },
      err => {
        console.log("errrrrrrrrrrrrrrrrr");
      }
    );
```

**Comment by jaredpalmer** [comment]
@ctrlplusb I came a across a potential use case for this...LinkedIn's desktop search sidebar, which basically submits the search form and navigates to the correct url upon each changed filter

**Comment by ctrlplusb** [comment]
Ok, rad, would you like me to resolve the conflicts in prep for merge?

**Comment by jaredpalmer** [comment]
Shoot it looks like you accidentally forgot to delete es6, lib, folders and accidentally checked in build output. Not a big deal (Formik is only 1.5kb).

Can you open a PR into the 0.8 branch instead of master?

**Comment by ctrlplusb** [comment]
argh, my bad, shall do.

**Comment by anhldbk** [comment]
@ctrlplusb Please make `submitForm` return a Promise also

**Comment by ctrlplusb** [comment]
@anhldbk there is no need. you can create a wrapper to satisfy this requirement. I will share when I have time on Monday. Weekending with family at mo.

**Comment by JuanpiRossi** [comment]
@ctrlplusb Could you please add an example?
Thanks

**Comment by bionicvapourboy** [comment]
@ctrlplusb, any examples ?

**Comment by cmswalker** [comment]
@JuanpiRossi @bionicvapourboy and for those of you still interested in this. Here is an example with the HOC boilerplate from the readme.

```
import React from 'react';
import { withFormik } from 'formik';

const InnerForm = ({
  values,
  errors,
  touched,
  handleChange,
  handleBlur,
  handleSubmit,
  isSubmitting,
  onSubmit // this is from our wrapper
}) => (
  <form onSubmit={(e) => {
    e.preventDefault();
    onSubmit(errors, values);
  }}>
    <input
      type="email"
      name="email"
      onChange={handleChange}
      onBlur={handleBlur}
      value={values.email}
    />
    {touched.email && errors.email && <div>{errors.email}</div>}
    <input
      type="password"
      name="password"
      onChange={handleChange}
      onBlur={handleBlur}
      value={values.password}
    />
    {touched.password && errors.password && <div>{errors.password}</div>}
    <button type="submit" disabled={isSubmitting}>
      Submit
    </button>
  </form>
);

const MyForm = withFormik({
  // Transform outer props into form values
  mapPropsToValues: props => ({ email: '', password: '' })
})(InnerForm);

const onSubmit = (errors, values) => {
  console.log('triggered formik from the outside world, keep in mind, this wont fire unless validation criteria is met FIRST');
  console.log('errors', errors);
  console.log('values', values);
}

const Basic = () => (
  <div>
    <h1>My Form</h1>
    <p>This can be anywhere in your application</p>
    <MyForm onSubmit={onSubmit}/>
  </div>
);

export default Basic;
```

**Comment by cmswalker** [comment]
@JuanpiRossi @bionicvapourboy and for those wanting an example on how to trigger formik `onSubmit` from the outside world. All you have to do is pass event props and registration props down to formik.

Here is an example with some modifications to the HOC boilerplate in the readme
```
import React from 'react';
import { withFormik } from 'formik';

const InnerForm = ({
  values,
  errors,
  touched,
  handleChange,
  handleBlur,
  handleSubmit,
  isSubmitting,
  onSubmitParent, // this is from our wrapper(parent) component
  registerSubmitElement // this is how we register the formik button that triggers onSubmit
}) => (
  <form onSubmit={(e) => {
    e.preventDefault();
    onSubmitParent(errors, values);
  }}>
    <input
      type="email"
      name="email"
      onChange={handleChange}
      onBlur={handleBlur}
      value={values.email}
    />
    {touched.email && errors.email && <div>{errors.email}</div>}
    <input
      type="password"
      name="password"
      onChange={handleChange}
      onBlur={handleBlur}
      value={values.password}
    />
    {touched.password && errors.password && <div>{errors.password}</div>}

    <div>{`We are hiding the formik form submit button with {display: 'none'}`}</div>
    <button style={{display: 'none'}} type="submit" disabled={isSubmitting} ref={button => registerSubmitElement(button)}>
      Submit
    </button>
  </form>
);

const MyForm = withFormik({
  // Transform outer props into form values
  mapPropsToValues: props => ({ email: '', password: '' })
})(InnerForm);

class Basic extends React.Component {
  constructor() {
    super();
    ['triggerSubmit', 'onSubmit', 'registerSubmitElement'].forEach(f => this[f] = this[f].bind(this));
  }

  registerSubmitElement(submitButton) {
    // NOTE: Registering the formik submit button into the Parent Component so we can trigger a click event
    this.submitButton = submitButton;
  }

  triggerSubmit() {
    // NOTE: Triggering the formik submit action from the outside world
    this.submitButton.click();
  }

  onSubmit(errors, values) {
    console.log('triggered formik onSubmit. Keep in mind, if you provide validation to formik, this wont fire unless validation criteria is met FIRST');
    console.log('errors', errors);
    console.log('values', values);
  }

  render() {
    return (
      <div>
        <h1>The formik form</h1>
        <MyForm triggerSubmit={this.triggerSubmit} onSubmitParent={this.onSubmit} registerSubmitElement={this.registerSubmitElement}/>
        <button onClick={() => this.triggerSubmit()}>A button outside of the formik form, located in the parent component</button>
      </div>
    );
  }
}

export default Basic;
```

**Comment by cmswalker** [comment]
@jaredpalmer I'd be happy to submit an example in either Readme or js form if you feel this would be helpful to add to the documentation or examples ^^ (I've seen it come up in a few issues, which is how I was led here)

**Comment by rivertam** [comment]
@cmswalker Thanks for the example!

Is this really the cleanest way we can do this? Having a fake button that gets passed up through a higher order function? I tend to only use "registration" functions as props when I'm deeply desperate for a better solution. I honestly haven't done it for months, and I don't think encouraging this behavior is really ideal.

My usecase is as follows: I'm making a form that I want to show up in multiple places. The main place it will show up is in a bootstrap modal. As anyone who uses bootstrap or similar knows, the proper way to do this is to put the submit button in the modal footer, while putting the form itself in the modal body. Therefore, I'd like to remotely trigger a submit from outside the form. There doesn't even seem to be a great way to change the outer component's state to match the values, much less a way to actually trigger validation.

I understand I can lift Formik up to a higher level and either pass down the props or use `<Field />` or the context more generally, but that would mean repeating the configuration or exposing the inner form as some kind of HOC that would wrap the outer component and pass the inner form as a prop... or maybe some other methodology I'm missing?

**Comment by cmswalker** [comment]
@rivertam seems like you could get away with formik's `renderProp` API for your use case instead of the HOC API.

According to the example here https://react-bootstrap.github.io/components/modal/

Would this not solve your use case?  Obviously it depends on if bootstrap is determining styles based on children order/types.

```
<div className="static-modal">
  <Modal.Dialog>
	<FORMIK START render={() => {
		{/* Do what you need w/ props + formik API */}
		<Modal.Header>
          <Modal.Title>Modal title</Modal.Title>
        </Modal.Header>

        <Modal.Body>One fine body...</Modal.Body>

        <Modal.Footer>
          <Button>Close</Button>
          <Button bsStyle="primary">Save changes</Button>
        </Modal.Footer>
    }}/>
  </Modal.Dialog>
</div>;
```

**Comment by rivertam** [comment]
@cmswalker I'm not sure I follow your example.... it doesn't seem to be valid JSX, so I think that's at least part of it.

However, I believe you're essentially suggesting I wrap the parent component in Formik rather than the form component. This would be fine if I only ever used the child form from the modal, but I also use the form from more typical use cases where I'm not wrapping it in a modal at all. So the validation part would need to get duplicated.

**Comment by cmswalker** [comment]
@rivertam it was pseudo-code. I've updated it with real code.

You're in a tricky situation. It's one I was facing with my team a few weeks ago, I had a form that was rendered in multiple places but sometimes it didn't need a submit button as it was being verified as just a component of a larger form, (whereas other times it was a standalone form with its own submit button)

The example I provided with the button and triggerSubmit props worked fine for us. We got it to work and wrote tests against it, but it just didn't "feel" very good. So we decided to duplicate a little bit of code vs poor abstraction (or at least, "icky" feeling abstraction).

So we ended up sharing all the input components, errorComponents, formikValidationSchemas and the visuals for the submit button but we wrote new components for the formWrapper itself. This actually helped others understand the formik API easier and leaves the door open to behavior changes in one variation of the form that the other one doesn't need (for example, what if one form is ajax but they other is a redirect? etc)

Hope you can make something work

**Comment by johnunclesam** [comment]
@rivertam have you some new thoughts on this problem?

I have too the modal problem. I don't like the `state` solution you proposed. How to handle this?

**Comment by rivertam** [comment]
I ended up sticking with the state solution. I really don't like it either, but I had to move on and it works.

**Pull request closed without merging**
