### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Add node 9 instead?

**Comment by DanielRuf** [comment]
> Add node 9 instead?

No, 8 is LTS and 10 is stable branch.

We have to update the affected dependency which uses `upath` (probably webpack according to the lock file but it is not in the package file).

**Comment by DanielRuf** [comment]
Will try to resolve it.

**Comment by DanielRuf** [comment]
`size-limit` is the root cause, we might just have to update the lockfile.

**Comment by DanielRuf** [comment]
Success =) I knew I saw this before in other projects and it is just because of upath 1.0.4 =)

So this can be also merged now.

**Pull request merged**
