### PR TITLE
fix: submitForm promise rejects if validation fails

### LINKED ISSUE #2958: submitForm returned promise not rejected if form is invalid
## Bug report

Promise is resolved both when form is valid and invalid.

### Expected behavior

According to the [docs](https://formik.org/docs/api/formik#submitform---promise) the promise should be rejected if the form is invalid.

### Reproducible example

https://codesandbox.io/s/formik-example-forked-ru3i1

Submit the form and check the console

### Suggested solution(s)

Reject the promise as specified in the docs

### Your environment

Check codesnabox example

### PR DESCRIPTION
**Pull request by Averethel**
Fixes #2958

### CODE REVIEW

**Comment by Averethel** [comment]
@jaredpalmer @johnrom anything I can do to get guidance here?

**Comment by johnrom** [comment]
I don't think throwing errors (usually known as exceptions in other languages) makes sense here. Exceptions are meant for exceptional behavior, and a form being invalid is not exceptional. It is not a state from which the application needs to recover.

I think it makes more sense to return a result which can indicate whether the submit actually went through.

It only really makes sense to me to throw if someone throws an error themselves within onSubmit, because the developer is basically throwing up their hands and saying they can't proceed with the code. Formik doesn't have that issue, it can simply not run onSubmit and the application will continue functioning normally.

**Comment by Averethel** [comment]
@johnrom Thank you for your answer. 
I stumbled upon this when I tried submitting the form programmatically, when I checked the docs the `submitForm` is documented as follow:

> Trigger a form submission. The promise will be rejected if form is invalid.

This is not the case when I have a `validation` function that returns an object containing errors, hence my change.

Let me try to explain my use-case and why I need to submit the form programmatically in the first place, maybe this helps to understand my motivation, or maybe there is another way to achieve what I want.
I have a very complex multi-step, branching, wizard style form. Depending on which submit action is used different things[1] could happen after submitting the form, but only if the submission is successful.
My previous approach was to use different `value` for submit buttons and handle success in the submission handler but with every new action the submission handler grew and was hard to maintain. Plus finding corresponding behaviours simply become a nightmare.

So I reached to `submitForm` and wanted to add the specific post submission handling in the event handlers on the buttons themselves. But, in the current implementation, there is no way of knowing if the submission did not happen at all because of failed validations. Maybe rethinking the approach is in order? What if `submitForm` was a promise returning a boolean instead of rejection if submission failed?


-----
[1] this could include navigating to a different step, revalidating the form with a different set of constraints, creating additional nested item, etc.

**Comment by johnrom** [comment]
I think it could return something. Probably not a boolean, because it's possible there could be more states in the future.

validation_failed, submit_failed, submit_success, submit_cancelled, etc

**Comment by Averethel** [comment]
@johnrom That makes sense, I like it. I take another look over the weekend and see how I can make that work

**Pull request closed without merging**
