### PR TITLE
implemented allowInvalidSubmission prop

### PR DESCRIPTION
**Pull request by julian-r**
Proposal

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Not sure why this got closed. Hrmmm. This not got wayyy too aggressive.

**Comment by jaredpalmer** [comment]
I wonder if we ought to make this function like `allowSubmit(state: FormikState): boolean` and pass that form state.

**Comment by miturostislav** [comment]
I'm dealing with a situation when I have to handle the failed submit. It may be worth  adding a new prop like `onFailedSubmit(errors: FormikErrors<any>, formikActions: FormikActions<Values>): void` and in case we want to submit the form anyway, we can do it in this function.

**Comment by matths** [comment]
#466 and #816 both got closed and never merged, although there have been PR with actual solutions to this kind of request. Why that? Is there a solution to this kind of problem at the moment?

**Pull request closed without merging**
