### PR TITLE
Automagically set <Field> type radio & checkbox `checked` and `value` props against form values

### PR DESCRIPTION
**Pull request by amcvitty**
Previously when creating a Field with `type="????"` to create a simple HTML component we were setting the `value` prop on all input components from the values object, but with this change we set `checked` for checkboxes and radio buttons, so that the state is synced with the values object (including its initial values) so the components are controlled (in React terminology).

Addresses issues #1050 #1024 and partly #1035

### CODE REVIEW

**Comment by amcvitty** [comment]
Note to reviewer: 
There are a bunch of `actual; injected;` in Field.test.tsx because I was seeing a lot of these noUnusedLocals warnings:
```
ERROR in [at-loader] ./test/Field.test.tsx:364:11 
    TS6133: 'actual' is declared but its value is never read.
```

The pattern there seems to be to capture the props in the component render to do assertions on it, but in a number of the tests, we don't have any assertions that make use of the variable. 
```
      let actual;
      const Component: React.SFC<FieldProps> = props =>
        (actual = props) && null;
```

I'm not usually a Typescript guy, so I'm not 100% sure what to do about this. Happy to just revert these changes

**Comment by jaredpalmer** [comment]
Agree

**Comment by prichodko** [comment]
I didn't want to take over your PR, but I already had most of the work done. Sorry for that. 

My proposed solution is here: https://github.com/jaredpalmer/formik/pull/1115

**Comment by Andreyco** [comment]
I consider this to be to specific and should be kept in user land. This would definitely not work when accepting multiple values for one field (multiple checked boxes for one field)... And other cases, for sure.

**Pull request closed without merging**
