### PR TITLE
hotfix: Revert throwing combined errors

### PR DESCRIPTION
**Pull request by jaredpalmer**
I confused myself this morning with 2.0.7. The change to submission is making formik unusable outside of react native. 

Revert changes in #1843

### CODE REVIEW

**Comment by HristoKolev** [comment]
You should publish a new version, the current is obviously not working.

Now I have to pin the package to 2.0.6 in package.json. (And then forget to unpin it...)

**Comment by benb1983** [comment]
+1

**Comment by uriklar** [comment]
I also found out my form was breaking in 2.0.8 (updated from 2.0.7)

This is how I use formik in my app:
```
<Formik
    initialValues={...some initial values}
    validationSchema={Yup.object().shape({
        ...some validations
    })}
    onSubmit={submit}>
    {formik => {
        return (
            <Form>
                ..some regular input fields
                    <button
                        type="submit"
                        onClick={e => {
                            e.preventDefault();
                            formik.submitForm().catch(errors => {
                                formik.setErrors(errors);
                            });
                        }}
                    />
                </div>
            </Form>
        );
    }}
</Formik>
```

I know this isn't the exact documented usage, but this is the only thing that worked (the throw line that was removed was causing the form to not catch it when there were validation errors)

Anyway, maybe I need to try a different implementation of the submit, but just FYI, this setup is broken on 2.0.8 (neither the `onSubmit` callback and then errors catch are being called)

**Comment by fabb** [comment]
Too bad this was reverted. I hoped there now was a better way to have side effects when submission was cancelled due to validation errors than this wrapper component:

```
export type FormikSubmitValidationErrorHandlerProps<Values> = FormikProps<Values> & {
    callback: () => void
}

export class FormikSubmitValidationErrorHandler<Values> extends React.Component<FormikSubmitValidationErrorHandlerProps<Values>> {
    componentDidUpdate(prevProps: FormikSubmitValidationErrorHandlerProps<Values>) {
        // formik currently does not call any callback in case submitting the form was aborted due to client validations, therefore we need a workaround
        if (prevProps.isSubmitting && !this.props.isSubmitting && !this.props.isValid) {
            this.props.callback()
        }
    }

    render() {
        return this.props.children
    }
}
```

https://github.com/jaredpalmer/formik/issues/146#issuecomment-327222858

**Pull request merged**
