### PR TITLE
Fix type for setFieldValue

### PR DESCRIPTION
**Pull request by niecnasowa**
setFieldValue returns Promise with {[field_name]: field_value}

### CODE REVIEW

**Comment by Stas-Buzunko** [comment]
why hasn't it been merged?

**Comment by danhorvath** [comment]
Is there an issue with this PR? how come it's not been merged yet?

**Comment by GLObus303** [comment]
Is there a plan to merge that PR? Is that correctly marked as an issue? By very basic test I could see promise being returned from the helper.

**Comment by ocho-cesar** [comment]
@jaredpalmer I think this PR is trivial and would be nice to get merged, thanks in advance

**Comment by SpencerKaiser** [comment]
I found #3465 and #2648 that all come back to this same issue from 2020... what's the hold up on getting this merged??

I ended up having to use `patch-package` to make this change locally because it's preventing me from using `FormikProps<MySchema>` 😕

**Comment by Renaud009** [comment]
Please merge this PR!

**Comment by cactusjames** [comment]
`setFieldValue` actually returns errors from validation, if `shouldValidate` is `true` or `undefined`, so I think the type should be:

```typescript
    setFieldValue(field: string, value: any): Promise<FormikErrors<Values> | undefined>;
    setFieldValue(field: string, value: any, shouldValidate: true): Promise<FormikErrors<Values> | undefined>;
    setFieldValue(field: string, value: any, shouldValidate: false): Promise<undefined>;
```

**Comment by Kepro** [comment]
3 years... (in a couple of days)

**Comment by Temetias** [comment]
dancing-coffin-coffin-dance

**Comment by kendallroth** [comment]
@jaredpalmer would it be possible to get this integrated into Formik? This would be very helpful, as it takes diving into source code to find out that `setFieldValue` actually returns a promise 🤷

**Pull request closed without merging**
