### PR TITLE
passed additional props to the `render` prop function

### PR DESCRIPTION
**Pull request by adsingh**
fixes bug #942

### CODE REVIEW

**Comment by adsingh** [comment]
If you think that the added test case creates duplication, I can merge it with the test above it.

**Comment by jaredpalmer** [comment]
Hey! Thanks for this. I used to think this was the move for a while. However, this pass thru in `render` is redundant. You can pass  props directly to the components that need them inside of `render` creating a closure.

**Comment by christianchown** [comment]
Hi @jaredpalmer, I'm not sure why this is closed off? Saying _"you can pass props directly to the components that need them inside of `render`"_ doesn't hold when using `Field` compositionally. Use case:

I have `class DecoratedField extends React.Component<{decoratedRenderProp}>`

DecoratedField is composed with a `<Field render={props.decoratedRenderProp} plusSomeOtherProps={whatever} />`

I would like to use it like
```
<CustomForm>
  <DecoratedField decoratedRenderProp=(({field, form, plusSomeOtherProps}) => ....} />
</CustomForm>
```
`plusSomeOtherProps` is only supplied by `DecoratedField` so is not available to me when composing a `CustomForm`, so I can't pass it directly in `render`. I am having to entertain some ridiculous structures to try to overcome this.

Or is there some other way of achieving this that I am not seeing?

**Comment by christianchown** [comment]
@kelkes I didn't get any reply, and this issue is marked as closed and https://github.com/jaredpalmer/formik/issues/942 is marked as "wontfix". Not sure it's going to get seen

However, I believe this should get fixed (and there's an inconsistency in that extra props are passed to components, but not to render functions or child-as-functions). Shall we open a new issue/PR?

**Comment by kelkes** [comment]
sure. lets do that!

**Comment by christianchown** [comment]
As @adsingh seems to have dropped off the mat, I'll fork his branch to add the required change from: https://github.com/jaredpalmer/formik/pull/957#issuecomment-430537213

**Pull request closed without merging**
