### PR TITLE
Fix #12. Use named exports

### LINKED ISSUE #12: Uncaught TypeError: (0 , _formik2.default) is not a function
I have been unable to get this to work. I'm importing Formik and exporting it as a HOC to my form component. Am I doing something wrong?

I get the following error:

**Error**
```console
client.bundle.js:18089 Uncaught TypeError: (0 , _formik2.default) is not a function
    at Object.defineProperty.value (client.bundle.js:18089)
    at __webpack_require__ (client.bundle.js:20)
    at Object.defineProperty.value (client.bundle.js:18390)
    at __webpack_require__ (client.bundle.js:20)
    at Object.<anonymous> (client.bundle.js:16873)
    at __webpack_require__ (client.bundle.js:20)
    at Object.defineProperty.value (client.bundle.js:19112)
    at __webpack_require__ (client.bundle.js:20)
    at validateFormat (client.bundle.js:66)
    at client.bundle.js:69
```

**Form.js**
```javascript
import React, { Component } from 'react';
import Formik from 'formik';
import Yup from 'yup';
import Grid from 'client/components/shared/grid';
import Form from 'client/components/shared/form';

class DonationForm extends Component {
  render() {
    const { values = {} } = this.props;
    return (
      <form>
        <Grid width="50" mobile="100">
          <Form.Input
            label="First Name"
            value={values.first_name}
          />
        </Grid>
        <Grid width="50" mobile="100">
          <Form.Input
            label="Last Name"
            value={values.last_name}
          />
        </Grid>
        <Grid width="50" mobile="100">
          <Form.Input
            label="Email Address"
            value={values.email_address}
          />
        </Grid>
        <Grid width="50" mobile="100">
          <Form.Input
            label="Phone Number"
            value={values.phone_number}
          />
        </Grid>
      </form>
    );
  }
}

const validationSchema = Yup.object().shape({
  first_name: Yup.string().required(),
  last_name: Yup.string().required(),
  email_address: Yup.string().email().required(),
  phone_number: Yup.string().required()
});
export default Formik({ validationSchema })(DonationForm);
```

### PR DESCRIPTION
**Pull request by jaredpalmer**
This fixes a bug for non-TypeScript users with importing from a module that exports both named and `default` exports. Unfortunately, it looks like the only solution is to switch to 
`import { Formik } from 'formik';`

### CODE REVIEW

**Comment by eonwhite** [comment]
I'm in favor of this, I'm not a huge fan of the default export anyway.

**Comment by jaredpalmer** [comment]
agreed @eonwhite, i will push changes internally to admin etc now

**Comment by jaredpalmer** [comment]
just bumped and published 0.7 so readme matches current version. lmk if you have issues. @quentin-sommer thanks for taking the time to report this. you rock.

**Comment by quentin-sommer** [comment]
Did I? I think you might have mistyped the name :p

**Comment by jaredpalmer** [comment]
Sorry it was @coreyleelarson. 😄

**Pull request merged**
