### PR TITLE
Add Field, FastField, ArrayField meta data props

### PR DESCRIPTION
**Pull request by prichodko**
There was a PR https://github.com/jaredpalmer/formik/pull/167, which unfortunately didn't land. However I would really love to see this landed, so I am taking this over. 

PR adds `meta` object to `Field` bag to ease getting of different states. Currently `meta` object consists of:

- error
- touched
- initial value

### Q
Is there anything we should add to it?

### WIP
- [ ] Documentation
- [x] Tests
- [x] Add meta to ArrayField

### Related issues
Resolves https://github.com/jaredpalmer/formik/issues/343
Resolves https://github.com/jaredpalmer/formik/issues/346

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Let’s add tests

**Comment by prichodko** [comment]
@jaredpalmer tests added. 

I extended `FieldArray` meta props to contain `touched`, `errors`, `initialValues` and `isEmpty`. Those values also default to empty array if they are undefined. So user can always just use `touched[index]` without the need to check if it exists.

I also added a prop which will be named after the `name` and will contain to values for the FieldArray (which also defaults to empty array). So for example:

```js
<FieldArray
 name="friends"
 render={({ friends }) => (
  {friends.map(f => ...)}
 )}
```

Lastly, the `FieldArray` rendering logic is updated so it's same as in `Field` & `FastField`.

**Comment by jaredpalmer** [comment]
This is a big breaking change. Not opposed to it though. Need to review

**Comment by prichodko** [comment]
@jaredpalmer, sure. If necessary I can break it in two separate PR's. `Field` & `FastField` meta `prop` and `FieldArray` enhancements.

**Comment by kheyse-oqton** [comment]
I came here looking for a solution for the FieldArray values problem, which could be solved with the proposal above:
```
<FieldArray
  name="friends"
  render={({ friends }) => (
    {friends.map(f => ...)}
  )}
/>
```

Personally, I'd choose not to name the prop after the name passed to FieldArray, because the name can contain full paths, e.g. `fb.friends`. Why not leave it in field.value? 
```
<FieldArray
    name="fb.friends"
    render={({ field, form }) => (field.value.map(friend => <Textarea value={friend} />)}
/>
```
This would be exactly the same as for the Field component.
```
<Field
     name="fb.friend"
     render={({ field, form }) => (<Textarea value={field.value} />)}
/>
```

**Comment by prichodko** [comment]
@jaredpalmer I will separate this PR into two parts, adding a `meta` prop for a regular `<Field />` seems like a no-brainer to me, we can have discussion about `<FieldArray />` in another PR.

**Comment by jaredpalmer** [comment]
Lets separate into 2 different PR's

**Comment by prichodko** [comment]
Closing in favor of: https://github.com/jaredpalmer/formik/pull/579.

**Pull request closed without merging**
