### PR TITLE
Add size-limit to prevent accidental bloat

### PR DESCRIPTION
**Pull request by prichodko**
After this https://github.com/jaredpalmer/formik/pull/513 great catch and huge decrease of bundle size, I decided to add [size-limit](https://github.com/ai/size-limit) to prevent from accidentally bundle something what would drastically increase it.

_Note:_ I noticed `prettier` on `formatOnSave` in VSCode formatted also `package.json`, but I decided to leave it, because it's being used in a library and `JSON` is supported format.

### CODE REVIEW

**Comment by vlad-zhukov** [comment]
This is good idea but wow, `size-limit` adds lots of dependencies. It looks like it uses `webpack` under the hood but we use rollup instead. Perhaps [`bundlesize`](https://github.com/siddharthkp/bundlesize) is a better candidate?

**Comment by prichodko** [comment]
@vlad-zhukov I was thinking about `bundlesize`. However there is a big difference between those two 
 - `bundlesize` outputs just a file sizes, `size-limit` shows the size of lib + it's dependencies (prevents unexpected huge dependency).

More info [here](https://github.com/ai/size-limit#comparison-with-bundlesize). What do you think?

**Comment by jaredpalmer** [comment]
What should we do here?

**Comment by prichodko** [comment]
Just merge, if you agree it's a good thing to have. Let me know and I will rebase the branch.

**Comment by jaredpalmer** [comment]
Lets rebase and get it going

**Comment by prichodko** [comment]
@jaredpalmer `next` or `master? 😄

**Comment by jaredpalmer** [comment]
next

**Comment by jaredpalmer** [comment]
Wait woah. Sorry I am out of it. Formik next is not what I want. I got confused because of how I am working on Razzle. Sorry about this. All against master. oof.

**Pull request merged**
