### PR TITLE
Add submitCount to Formik

### PR DESCRIPTION
**Pull request by prichodko**
Adds a property to state, which tracks number of times user tried to submit the form.

If we agree on the implementation, I will add related tests & documentation 🤖.

### WIP
- [x] Tests
- [x] Documentation

### Related issues
Resolves https://github.com/jaredpalmer/formik/issues/375

### CODE REVIEW

**Comment by prichodko** [comment]
@jaredpalmer I added necessary tests and also renamed test file, so it matches with this change - https://github.com/jaredpalmer/formik/pull/452.

However, @jaredpalmer could you elaborate how doctoc works? When I run it, I don't see any changes made.

**Comment by jaredpalmer** [comment]
you need to run `doctoc readme.md`

**Comment by jaredpalmer** [comment]
What happens when resetForm is called?

**Comment by prichodko** [comment]
Great catch @jaredpalmer, thanks. Fixed and test added.

**Comment by jaredpalmer** [comment]
LGTM

**Pull request merged**
