### PR TITLE
Fix #673. Fix fastfield using cDU

### LINKED ISSUE #673: FastField "field.value" doesn't get typed value
**Describe the bug**

The FastField component seems to not be passing the the keyboard typed value into the `field.value` injected prop of a custom input component, since this prop is passed down to the inner input of the field, the typed text dosen't get rendered (this happens too if we don't use a custom input component).

**To Reproduce**

Checkout the following sandbox and start typing in the input.

[Edit Formik and Material-ui](https://codesandbox.io/s/1478jo353), 

**Expected behavior**

The input should display all typed characters.

**Suggested solution(s)**

I tracked back some earlier versions and it looks like the issue was introduced at version 1.0.0-alpha.r16.3.1

**Additional context**

I'm still in the process on adopting the library, i'm trying to integrate FastField with Material-UI's TextField, I was able to integrate the normal Field component with Material-UI without any issue.

---

- Formik Version: v1.0.0-beta.2
- React Version: 16.3.2
- TypeScript Version: N/A
- CodeSandbox Link: [here](https://codesandbox.io/embed/1478jo353)
- OS: Windows 10
- Node Version: N/A
- Package Manager and Version: N/A

### PR DESCRIPTION
**Pull request by jaredpalmer**
I (think) this fixes `<FastField>` on 16.4. I wasn't sure if we should do this in `componentDidUpdate` or if we should do this by storing old props on state and use `getDerivedStateFromProps`

https://reactjs.org/blog/2018/05/23/react-v-16-4.html#2-compare-incoming-props-to-previous-props-when-computing-controlled-values

### CODE REVIEW

**Comment by prichodko** [comment]
Random thought:

Does it mean that if parent for some reason re-renders with different `value`, your `value` (in a state) would be overwritten? Can it even happen in inputs? 🤔

**Comment by prichodko** [comment]
Why do we use this then - https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L422? If there is a check inside the `FastField` component, which should reset it when parent updates state with new values.

**Comment by jaredpalmer** [comment]
I think you are right. I don't think we need the resetFn anymore.

**Comment by jaredpalmer** [comment]
I wonder if we should move fastfield to just use sCU instead of trying to sync up local state.

**Comment by prichodko** [comment]
What if regular `Field` implemented sCU?

**Comment by prichodko** [comment]
If it would make sense, I can create a PR - do we have some project to test it out?

**Comment by jaredpalmer** [comment]
i can test it on a big app. I think FastField should implement sCU the more i think about it.

**Comment by prichodko** [comment]
Do you think regular `<Field />` with SCU could be as performant as `<FastField />` ?

**Comment by jaredpalmer** [comment]
After this release I think I am going to move FastField to use sCU.

**Comment by vlad-zhukov** [comment]
There is also no need to use react-lifecycles-compat for this component!

**Comment by AaronW9090** [comment]
>Do you think regular <Field /> with SCU could be as performant as <FastField /> ?

This is true except that the issue isn't just Fields that are being updated, it's everything that Formik wraps. This could be an arbitrarily deep component tree that is re-rendering for no reason. It's especially a problem when using the withFormik HOC because it's less clear what is being controlled by Formik.

No reason not to implement sCU into Field anyway but it doesn't completely solve the performance issue.

**Pull request merged**
