### PR TITLE
Add forwardref to Formik

### PR DESCRIPTION
**Pull request by drivasperez**
Tentatively solves #2208, maybe.

### CODE REVIEW

**Comment by jaredpalmer** [comment]
This doesn't work AFAICT because of the generics.

https://github.com/jaredpalmer/formik/pull/2209/checks?check_run_id=389788052#step:5:128

**Comment by drivasperez** [comment]
Yeah, I realised as soon as I made the PR. I should have run the tests locally before pushing, sorry.

Trying some really hair-raising things with casting before work, but have run out of time for the moment. Starting to think innerRef is just the better solution.

**Comment by drivasperez** [comment]
@jaredpalmer This now builds and passes the existing tests, and if you pass a ref, it gets the formikbag. Is the codesandbox environment broken, or have I done something wrong?

**Comment by jaredpalmer** [comment]
Codesandbox is broken.

**Comment by drivasperez** [comment]
Ah, okay. Do you think something like this is worth the typescript weirdness?

**Pull request closed without merging**
