### PR TITLE
Revert "Replace 'any' on <Form /> with proper types (#730)"

### PR DESCRIPTION
**Pull request by jaredpalmer**
This reverts commit 7fc86da2114933b59f0176ab42a9aa07fb6a5647.

### CODE REVIEW

**Comment by tgriesser** [comment]
Ah what happened?

**Comment by jaredpalmer** [comment]
@tgriesser When was Exclude introduced into TypeScript?

**Comment by jaredpalmer** [comment]
@tgriesser It was added in 2.8 or 2.9 with conditional types (i think) https://github.com/Microsoft/TypeScript/commit/2aba29fc32b21cd9f56ea8510c37772735ebcadf

**Comment by tgriesser** [comment]
Oh yeah, 2.8. I saw 2.9 as the target in the package.json so I figured it was alright to use, still not fully familiar with best practices around TS backward compat when authoring modules.

**Comment by jaredpalmer** [comment]
@weswingham any thoughts on best practices here? What do other large TS projects do? What happens when an old version of TS encounters a newer feature?

**Comment by jaredpalmer** [comment]
Screw it. We’re on 2.9 lol

**Pull request closed without merging**
