### PR TITLE
Chore/bump deepmerge to v4.2.2

### PR DESCRIPTION
**Pull request by Pearce-Ropion**
**What did I change**
[Chore] Updated dependency `deepmerge` to latest version (v4.2.2)
[Change] Updated `arrayMerge` function to match [deepmerge documentation](https://github.com/TehShrike/deepmerge/tree/v4.2.2#arraymerge-example-combine-arrays)

I also made sure to check `deepmerge`'s changelog for any breaking changes.

**Reasoning**
Gatsby recently added `deepmerge` as a dependency. Conflicting versions of `deepmerge` can cause gatsby builds to fail on gatsby v3.14.0 and later.
See https://github.com/gatsbyjs/gatsby/issues/33274 for more details

**Test Plan**
Run `yarn test` - all tests pass
Run `yarn start:app`
Run `yarn cypress` - all tests pass

### CODE REVIEW

**Comment by dmorda** [comment]
Any ETA on this one? It's currently blocking upgrades to Gatsby short of temporarily switching to yarn to better resolve dependencies.

**Comment by AsathalMannan** [comment]
Still gatsby build failing,.. please consider this PR.

**Comment by Pearce-Ropion** [comment]
For anyone coming here from gatsby, I recommend you use version 3.13.1. ￼Alternatively, you can try forking my PR and bundling the code yourselves as a temporary stopgap until this PR gets merged. 

Unfortunately, it looks like this repo has had very little activity on it in recent months so I have no idea when that will be.

**Comment by sallakos** [comment]
Please consider this PR. Any ETA?

**Comment by sallakos** [comment]
Still waiting, please could @jaredpalmer or @johnrom review this?

**Comment by surreum** [comment]
Impossible to update Gatsby. Please fix.

**Comment by Pearce-Ropion** [comment]
Closing as there has been no indication that the Formik team plans to merge this. Feel free to re-open if any traction happens here.

**Pull request closed without merging**
