### PR TITLE
Added ESM build

### PR DESCRIPTION
**Pull request by retyui**
https://github.com/jaredpalmer/formik/issues/643

### CODE REVIEW

**Comment by retyui** [comment]
@TrySound 
I attach a link to the issues https://github.com/jaredpalmer/formik/issues/643

------------------------------------------------------------------------------------------
**Is your feature request related to a problem? Please describe.**
I try reduce my bundels size. In my project I use one import:
```js
import { withFormik } from 'formik';
```
I would like to have the opportunity to do so:
```js
import withFormik from 'formik/esm/withFormik';
```

**Describe the solution you'd like**
Why do you collect code in a single js bundle?
Use flatten struct!
Like as: `lodash-es`, `date-fns`, `react-router`, `ramda`, `recompose`

**Comment by retyui** [comment]
@jaredpalmer help me!

**Comment by TrySound** [comment]
This is actually a bad solution which creates the problem of large import statements sections. It's better to provide better treeshakability. By the way recompose is gonna remove path imports.

**Comment by retyui** [comment]
Example:
https://unpkg.com/react-redux@5.0.7/
This module is very user friendly.
if I do not need a bundle, I will use the import from the `dist` folder
if I need the cmj version I'm doing the import from the `lib` folder
if I need the version I can use the import from the `es` or `src` folder

Now for some reason you decided to represent the entire bundle.

**Comment by TrySound** [comment]
The problem is that you should choose the way to import. But you don't need to choose. Just use single entry point and do not care about package structure.

But the way that package is not friendly. The import is not universal you should choose also cjs or esm. If you choose esm then you cannot run this code in node without transpiling node_modules and if you choose cjs your bundle will be bigger.

Use single entry point and allow bundler make all these decisions for you. If you care about bundle size then help to improve treeshakability. I created a tool for tracking (https://github.com/TrySound/rollup-plugin-size-snapshot).

**Comment by retyui** [comment]
@TrySound 
> This is actually a bad solution which creates the problem of large import statements sections

In our case, there is no such problem!

> If you care about bundle size then help to improve treeshakability. 

I use webpack 4 and tree shaking doesn't work there.
 
Who does not care about the size of the original files, let them use your single entry point.

I have a rigid frame for file sizes. And I already chose the import method. Only formik does not support this method. Why do you oppose?

**Comment by TrySound** [comment]
@retyui Treeshaking works if library code and configuration doesn't suck. The problem of this library is top level function calls and transpiled classes without pure annotations (is the a config option or TS sucks here?). Prefering babel over typescript could solve the problem.

**Comment by retyui** [comment]
I created a test repository, tell me please who sucks the configuration or module?
https://github.com/retyui/test

**Comment by TrySound** [comment]
I mean config in formik build process, it's not user land problem. The point is that untranspiled code is treeshakable enough, some cases can be handled with pure annotations. Transpiled code has problems which can be solved with the right configuration.

**Comment by retyui** [comment]
@TrySound 
If not our problem - Then I suggest you now in the lodash-es repository
and create an issue, about not need to provide untranspiled code 
and that the functionality of this library would be in one file

**Comment by TrySound** [comment]
lodash suck because of default export which has a bunch of effects. Simple reexports will works perfectly.
https://unpkg.com/lodash-es@4.17.10/lodash.default.js

**Comment by retyui** [comment]
@TrySound It will take a lot of time? Can I help?

**Comment by jaredpalmer** [comment]
I would prefer to stay with TypeScript. We are going to be updating stuff for TS 2.9 as soon as it drops

**Comment by TrySound** [comment]
@jaredpalmer Well is there a way to disable transpiling class properties in typescript?

**Comment by TrySound** [comment]
Yeah, I use it too.

**Comment by TrySound** [comment]
There's some problem with ts generated code elimination. Trying to figure out what he problem.

**Comment by klis87** [comment]
For a proper webpack tree shaking, pls also add `"sideEffects": false` to `package.json` - I assume there is no sideeffect in this lib so reexports are safe not to include them when they are not imported

**Comment by TrySound** [comment]
Waiting this for merge so we could prove treeshakability.
https://github.com/jaredpalmer/formik/pull/593

**Pull request closed without merging**
