### PR TITLE
Add SwissDev DevOps Jobs as formik user

### PR DESCRIPTION
**Pull request by Vrq**

### CODE REVIEW

**Comment by Vrq** [comment]
@jaredpalmer could you have a look? :)

**Comment by Vrq** [comment]
@johnrom, @CoreyAR could you check it out, it is a small one? :)

**Comment by johnrom** [comment]
Unfortunately, I don't manage Formik's users. Sorry!

**Comment by CoreyAR** [comment]
I enjoy using the library and helping answer questions / contributing but I'm not affiliated with Formik so I don't have any input on this PR.

**Comment by Vrq** [comment]
@jaredpalmer perhaps? 😄

**Comment by Vrq** [comment]
Hi @jaredpalmer would you mind having a look?

**Comment by jaredpalmer** [comment]
Do you have an svg?

**Comment by Vrq** [comment]
@jaredpalmer sure, changed to SVG.

**Comment by Vrq** [comment]
@jaredpalmer is it fine now? :)

**Comment by Vrq** [comment]
@jaredpalmer how about now? :)

**Pull request merged**
