### PR TITLE
Update Field structure, add meta props

### PR DESCRIPTION
**Pull request by VladShcherbin**
Proposal for updated `Field` props structure:

```js
const field = {
  input: {
    name,
    value,
    onChange,
    onBlur
  },
  meta: {
    dirty,
    error,
    initialValue,
    pristine,
    touched
  }
}
```

Very useful in custom components:

1. Show error

```js
// before
{form.touched[field.name] && form.errors[field.name] && (
  <p>{form.errors[field.name]</p>
)}

// after
{field.meta.touched && field.meta.error && (
  <p>{field.meta.error}</p>
})

// after with FieldError component
<FieldError state={field.meta} />
```

2. Reuse meta props in component functions, components

```js
// before
const fieldState = {
  touched: form.touched[field.name],
  error: form.errors[field.name]
}

const fieldClassName = generateFieldClassName(fieldState)

<input className={fieldClassName} {...field} />
<FieldError state={fieldState} />

// after
const fieldClassName = generateFieldClassName(field) // or pass `field.meta`

<input className={fieldClassName} {...field.input} />
<FieldError state={field} /> // or pass `field.meta`
```

TODO:

- [x] Add `initialValue` meta prop
- [x] Add `pristine` / `dirty` meta prop
- [x] Update typings
- [x] Update docs
- [x] Add example

### CODE REVIEW

**Comment by VladShcherbin** [comment]
Another idea: it's possible to add this directly to `field` prop to be more clean. In this case, if we have a default (not custom) component, we just remove `meta` prop:

```js
const { meta, ...bag } = field
```

Thoughts?

**Comment by VladShcherbin** [comment]
@jaredpalmer hey, maybe you can have a quick look and tell, are you for or against this so I can continue?

**Comment by VladShcherbin** [comment]
Ready for review.

**Comment by thomastvedt** [comment]
I think this looks good, easy to spread input props to custom component, and nice to separate input props from metadata props. (I didn't look at the code)

**Comment by Landish** [comment]
This is an excellent PR, well done @VladShcherbin ! 

@jaredpalmer First of thanks, for having such a great library. I can see that you're working on V1, are you planing to merge this in the next major release?

**Comment by jaredpalmer** [comment]
This pr should be closed and a new one made to the `next` branch.

**Comment by VladShcherbin** [comment]
Closing this due to no activity and no interest from author.

**Comment by jaredpalmer** [comment]
I’m on vacation. Like I said I’m open to this, but should be merged into next branch

**Comment by jaredpalmer** [comment]
@VladShcherbin I'd like to merge this into `next`. Would you be willing to update it?

**Comment by VladShcherbin** [comment]
@jaredpalmer I switched to using another forms package and won't be able to update this, sorry.

**Pull request closed without merging**
