### PR TITLE
Replace warning

### PR DESCRIPTION
**Pull request by jaredpalmer**
Warning is not treeshakable :shrug:

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Errrrrr. Actually, I'm not sure this will work. the warning module provides the call stack, which is kinda nice. 

Also tiny-warning, uses `console.warn` while warning actually uses `console.error`

**Comment by TrySound** [comment]
Why error instead of warning? Error always frighten me when I see it in console.

**Comment by TrySound** [comment]
I can add call stack
https://github.com/alexreardon/tiny-warning/issues/2

**Comment by TrySound** [comment]
https://github.com/alexreardon/tiny-warning/pull/6

**Comment by TrySound** [comment]
Could you point me how throwing error helps with debugging? I see stack trace in both cases
https://codesandbox.io/s/l34rvm5r8z

**Comment by jaredpalmer** [comment]
Warning uses console.error. there is a full discussion about it in React repo somewhere. Not sure why we would change this behavior now.

**Comment by TrySound** [comment]
I found it. I understand why try catch there. But `console.error` reason seems like a legacy. I see stack trace with warning too. I just think that semantically error is too aggressive.

https://github.com/facebook/react/issues/4216

**Comment by jaredpalmer** [comment]
FWIW React still uses console.error https://github.com/facebook/react/blob/master/packages/shared/warningWithoutStack.js#L40

**Comment by TrySound** [comment]
Should we? The decision was made because of features lack in old browsers. Now it's probably a time to follow semantic. We may even rise an issue in react so they could migrate in v17.

**Comment by jaredpalmer** [comment]
Fair enough. We just need to update test harness.

**Comment by jaredpalmer** [comment]
This should work now

**Pull request merged**
